INSERT INTO courses(name, description) VALUES('ARCHITECTURE', 'Description ARCHITECTURE');
INSERT INTO courses(name, description) VALUES('COMPUTER SCIENCE', 'Description COMPUTER SCIENCE');
INSERT INTO courses(name, description) VALUES('ECONOMICS', 'Description ECONOMICS');
INSERT INTO courses(name, description) VALUES('GEOGRAPHY', 'Description GEOGRAPHY');
INSERT INTO courses(name, description) VALUES('HISTORY', 'Description HISTORY');
INSERT INTO courses(name, description) VALUES('LAW', 'Description LAW');
INSERT INTO courses(name, description) VALUES('MATHEMATICS', 'Description MATHEMATICS');
INSERT INTO courses(name, description) VALUES('MEDICINE', 'Description MEDICINE');
INSERT INTO courses(name, description) VALUES('PHILOSOPHY', 'Description PHILOSOPHY');
INSERT INTO courses(name, description) VALUES('SOCIOLOGY', 'Description SOCIOLOGY');
