TRUNCATE student_course;
TRUNCATE students RESTART IDENTITY CASCADE;
TRUNCATE courses RESTART IDENTITY CASCADE;
TRUNCATE groups RESTART IDENTITY CASCADE;
INSERT INTO courses(id, name, description) VALUES(1, 'ARCHITECTURE', 'Description ARCHITECTURE');
INSERT INTO courses(id, name, description) VALUES(2, 'COMPUTER SCIENCE', 'Description COMPUTER SCIENCE');
INSERT INTO courses(id, name, description) VALUES(3, 'ECONOMICS', 'Description ECONOMICS');
INSERT INTO courses(id, name, description) VALUES(4, 'GEOGRAPHY', 'Description GEOGRAPHY');
INSERT INTO courses(id, name, description) VALUES(5, 'HISTORY', 'Description HISTORY');
INSERT INTO courses(id, name, description) VALUES(6, 'LAW', 'Description LAW');
INSERT INTO courses(id, name, description) VALUES(7, 'MATHEMATICS', 'Description MATHEMATICS');
INSERT INTO courses(id, name, description) VALUES(8, 'MEDICINE', 'Description MEDICINE');
INSERT INTO courses(id, name, description) VALUES(9, 'PHILOSOPHY', 'Description PHILOSOPHY');
INSERT INTO courses(id, name, description) VALUES(10, 'SOCIOLOGY', 'Description SOCIOLOGY');
ALTER SEQUENCE courses_id_seq RESTART WITH 25;
INSERT INTO students(id, group_id, last_name, first_name)  VALUES (1, null, 'Henris', 'Mia');
INSERT INTO students(id, group_id, last_name, first_name)  VALUES (2, null, 'Green', 'Victoria');
INSERT INTO students(id, group_id, last_name, first_name)  VALUES (3, null, 'Hoig', 'Adrian');
INSERT INTO students(id, group_id, last_name, first_name)  VALUES (4, null, 'Johnson', 'Jack');
INSERT INTO students(id, group_id, last_name, first_name)  VALUES (5, null, 'Walker', 'Logan');
ALTER SEQUENCE students_id_seq RESTART WITH 25;
INSERT INTO student_course(student_id, course_id)  VALUES (1, 8);
INSERT INTO student_course(student_id, course_id)  VALUES (1, 6);
INSERT INTO student_course(student_id, course_id)  VALUES (2, 2);
INSERT INTO student_course(student_id, course_id)  VALUES (3, 9);
INSERT INTO student_course(student_id, course_id)  VALUES (3, 2);
INSERT INTO student_course(student_id, course_id)  VALUES (4, 3);
INSERT INTO student_course(student_id, course_id)  VALUES (5, 7);
INSERT INTO student_course(student_id, course_id)  VALUES (5, 10);
