TRUNCATE student_course;
TRUNCATE students RESTART IDENTITY CASCADE;
TRUNCATE courses RESTART IDENTITY CASCADE;
TRUNCATE groups RESTART IDENTITY CASCADE;
INSERT INTO courses(id, name, description) VALUES(1, 'ARCHITECTURE', 'Description ARCHITECTURE');
INSERT INTO courses(id, name, description) VALUES(2, 'COMPUTER SCIENCE', 'Description COMPUTER SCIENCE');
INSERT INTO courses(id, name, description) VALUES(3, 'ECONOMICS', 'Description ECONOMICS');
INSERT INTO courses(id, name, description) VALUES(4, 'GEOGRAPHY', 'Description GEOGRAPHY');
INSERT INTO courses(id, name, description) VALUES(5, 'HISTORY', 'Description HISTORY');
INSERT INTO courses(id, name, description) VALUES(6, 'LAW', 'Description LAW');
INSERT INTO courses(id, name, description) VALUES(7, 'MATHEMATICS', 'Description MATHEMATICS');
INSERT INTO courses(id, name, description) VALUES(8, 'MEDICINE', 'Description MEDICINE');
INSERT INTO courses(id, name, description) VALUES(9, 'PHILOSOPHY', 'Description PHILOSOPHY');
INSERT INTO courses(id, name, description) VALUES(10, 'SOCIOLOGY', 'Description SOCIOLOGY');
ALTER SEQUENCE courses_id_seq RESTART WITH 25;
INSERT INTO groups(id, name) VALUES (1, 'EM-32');
INSERT INTO groups(id, name) VALUES (2, 'UJ-33');
INSERT INTO groups(id, name) VALUES (3, 'FE-22');
INSERT INTO groups(id, name) VALUES (4, 'NU-88');
INSERT INTO groups(id, name) VALUES (5, 'CI-37');
INSERT INTO groups(id, name) VALUES (6, 'AR-49');
INSERT INTO groups(id, name) VALUES (7, 'KK-73');
INSERT INTO groups(id, name) VALUES (8, 'QR-95');
INSERT INTO groups(id, name) VALUES (9, 'RI-47');
INSERT INTO groups(id, name) VALUES (10, 'IC-83');
ALTER SEQUENCE groups_id_seq RESTART WITH 25;
