INSERT INTO students(id, group_id, last_name, first_name)  VALUES (1, 2, 'Henris', 'Mia');
INSERT INTO students(id, group_id, last_name, first_name)  VALUES (2, null, 'Green', 'Victoria');
INSERT INTO students(id, group_id, last_name, first_name)  VALUES (3, 7, 'Hoig', 'Adrian');
INSERT INTO students(id, group_id, last_name, first_name)  VALUES (4, 1, 'Johnson', 'Jack');
INSERT INTO students(id, group_id, last_name, first_name)  VALUES (5, 3, 'Walker', 'Logan');
INSERT INTO students(id, group_id, last_name, first_name)  VALUES (6, 1, 'Perez', 'Jackson');
INSERT INTO students(id, group_id, last_name, first_name)  VALUES (7, 2, 'Perez', 'Samuel');
INSERT INTO students(id, group_id, last_name, first_name)  VALUES (8, null, 'Miller', 'Olivia');
INSERT INTO students(id, group_id, last_name, first_name)  VALUES (9, 1, 'Thompson', 'Scarlett');
ALTER SEQUENCE students_id_seq RESTART WITH 25;
